### ISSUE TITLE
add test for typescript

### ISSUE THREAD

**Issue by tkellen** [tkellen/node-rechoir#18]
@pspeter3 before I release https://github.com/tkellen/node-interpret/commit/9ab5b40b72b20cbe01e110eeb1c12315e2de2003, can you please add a passing test for typescript?

**Comment by pspeter3** [comment]
Yep. This is on my to do list for today

**Comment by pspeter3** [comment]
This is closed in https://github.com/tkellen/node-rechoir/pull/19
